site_name: Akhilesh's Interview Prep
theme: material

nav:
  - Home: index.md
  - ML Prep: ml_prep.md
  - Neural Networks: neural-networks.md
  - GenAI: gen_ai.md
  - Research Papers: research.md
  - Useful Links: external_links.md